version: '3.8'

services:
  # --------------------------------------- [minio OCS]
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    networks:
      - ocs-network
    volumes:
      - minio-storage:/data
  # ---------------------------------------
  # --------------------------------------- [prometheus0_eu1]
  prometheus0_eu1:
    container_name: prometheus0_eu1
    # restart: unless-stopped
    image: prom/prometheus:v3.4.1
    user: root
    networks:
      - prometheus-eu-network
    # network_mode: host # Use host network stack
    volumes:
      # - ./prometheus0_eu1_data:/etc/prometheus
      - prometheus0-eu1-storage:/prometheus
      - ./prometheus0_eu1.yml:/etc/prometheus/prometheus.yml:ro
      - ./node_exporter.crt:/etc/node_exporter/node_exporter.crt:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.listen-address=:9090'
      # - "--web.external-url=https://8d91acbb5065-10-244-8-65-9090.spch.r.killercoda.com"
      - --web.enable-lifecycle
      - --web.enable-admin-api
      - --storage.tsdb.min-block-duration=15m
      - --storage.tsdb.max-block-duration=15m
      - --storage.tsdb.retention.time=12h
    ports:
      - 9090:9090

  thanos_sidecar_eu1:
    container_name: prometheus-0-sidecar-eu1
    image: quay.io/thanos/thanos:v0.39.1
    user: root
    restart: unless-stopped
    networks:
      - prometheus-eu-network
      - ocs-network
    depends_on:
      - prometheus0_eu1
    volumes:
      - ./prometheus0_eu1.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/bucket-storage.yml:/etc/thanos/minio-bucket.yml:ro
      - prometheus0-eu1-storage:/prometheus
    command:
      - sidecar
      - --http-address=0.0.0.0:19090
      - --grpc-address=0.0.0.0:19190
      - --reloader.config-file=/etc/prometheus/prometheus.yml
      - --reloader.watch-interval=15s # default 3m
      - --prometheus.url=http://prometheus0_eu1:9090
      - --objstore.config-file=/etc/thanos/minio-bucket.yml
      - --tsdb.path=/prometheus

      - --shipper.upload-compacted # Upload compacted blocks to the object store, just for first time
    ports:
      - 19090:19090
      - 19190:19190

  # --------------------------------------- [prometheus0_us1]
  prometheus0_us1:
    container_name: prometheus0_us1
    # restart: unless-stopped
    image: prom/prometheus:v3.4.1
    user: root
    networks:
      - prometheus-us0-network
    # network_mode: host # Use host network stack
    volumes:
      # - ./prometheus0_us1_data:/etc/prometheus
      - prometheus0-us1-storage:/prometheus
      - ./prometheus0_us1.yml:/etc/prometheus/prometheus.yml:ro
      # - ./node_exporter.crt:/etc/node_exporter/node_exporter.crt:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.listen-address=:9090'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - --storage.tsdb.min-block-duration=15h
      - --storage.tsdb.max-block-duration=15h
      - --storage.tsdb.retention.time=12h
    ports:
      - 9091:9090

  thanos_sidecar0_us1:
    container_name: prometheus-0-sidecar-us1
    image: quay.io/thanos/thanos:v0.39.1
    user: root
    restart: unless-stopped
    networks:
      - prometheus-us0-network
      - ocs-network
    depends_on:
      - prometheus0_us1
    volumes:
      - ./prometheus0_us1.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/bucket-storage.yml:/etc/thanos/minio-bucket.yml:ro
      - prometheus0-us1-storage:/prometheus
    command:
      - sidecar
      - --http-address=0.0.0.0:19090
      - --grpc-address=0.0.0.0:19190
      - --reloader.config-file=/etc/prometheus/prometheus.yml
      - --reloader.watch-interval=15s # default 3m
      - --prometheus.url=http://prometheus0_us1:9090
      - --objstore.config-file=/etc/thanos/minio-bucket.yml
      - --tsdb.path=/prometheus
      - --shipper.upload-compacted # Upload compacted blocks to the object store, just for first time
    ports:
      - 19091:19090
      - 19191:19190

  # --------------------------------------- [prometheus1_us1]
  prometheus1_us1:
    container_name: prometheus1_us1
    # restart: unless-stopped
    image: prom/prometheus:v3.4.1
    user: root
    networks:
      - prometheus-us1-network
    volumes:
      # - ./prometheus1_us1_data:/etc/prometheus
      - prometheus1-us1-storage:/prometheus
      - ./prometheus1_us1.yml:/etc/prometheus/prometheus.yml:ro
      # - ./node_exporter.crt:/etc/node_exporter/node_exporter.crt:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.listen-address=:9090'
      # - "--web.external-url=https://8d91acbb5065-10-244-8-65-9090.spch.r.killercoda.com"
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - --storage.tsdb.min-block-duration=15m
      - --storage.tsdb.max-block-duration=15m
      - --storage.tsdb.retention.time=12h
    ports:
      - 9092:9090

  thanos_sidecar1_us1:
    container_name: prometheus-1-sidecar-us1
    image: quay.io/thanos/thanos:v0.39.1
    user: root
    restart: unless-stopped
    networks:
      - prometheus-us1-network
      - ocs-network
    depends_on:
      - prometheus1_us1
    volumes:
      - ./prometheus1_us1.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/bucket-storage.yml:/etc/thanos/minio-bucket.yml:ro
      - prometheus1-us1-storage:/prometheus
    command:
      - sidecar
      - --http-address=0.0.0.0:19090
      - --grpc-address=0.0.0.0:19190
      - --reloader.config-file=/etc/prometheus/prometheus.yml
      - --reloader.watch-interval=15s # default 3m
      - --prometheus.url=http://prometheus1_us1:9090
      - --objstore.config-file=/etc/thanos/minio-bucket.yml
      - --tsdb.path=/prometheus
      - --shipper.upload-compacted # Upload compacted blocks to the object store, just for first time
    ports:
      - 19092:19090
      - 19192:19190

  # --------------------------------------- [thanos_querier]
  thanos_querier:
    container_name: thanos_query
    image: quay.io/thanos/thanos:v0.39.1
    networks:
      - prometheus-eu-network
      - prometheus-us0-network
      - prometheus-us1-network
      - querier-network
    restart: unless-stopped
    depends_on:
      - thanos_sidecar_eu1
      - thanos_sidecar0_us1
      - thanos_sidecar1_us1
      - thanos_store_gateway
    ports:
      - 29090:29090
    command:
      - 'query'
      - '--http-address=0.0.0.0:29090'
      - '--query.replica-label=replica'
      - '--endpoint=thanos_sidecar_eu1:19190'
      - '--endpoint=thanos_sidecar0_us1:19190'
      - '--endpoint=thanos_sidecar1_us1:19190'
      - '--endpoint=thanos_store_gateway:19191'
  #----------------------------------------
  #---------------------------------------- [Store Gateway]
  thanos_store_gateway:
    container_name: thanos_store_gateway
    image: quay.io/thanos/thanos:v0.39.1
    user: root
    networks:
      - ocs-network
      - querier-network
    restart: unless-stopped
    depends_on:
      - minio
    volumes:
      - ./config/bucket-storage.yml:/etc/thanos/minio-bucket.yml:ro
    ports:
      - 19094:19091
      - 19194:19191
    command:
      - 'store'
      - --objstore.config-file=/etc/thanos/minio-bucket.yml
      - --http-address=0.0.0.0:19091
      - --grpc-address=0.0.0.0:19191

  thanos_compactor:
    container_name: thanos_compactor
    image: quay.io/thanos/thanos:v0.39.1
    user: root
    volumes:
      - ./config/bucket-storage.yml:/etc/thanos/minio-bucket.yml:ro
    ports:
      - 19095:19095
    networks:
      - ocs-network
    restart: unless-stopped
    command:
      - 'compact'
      - --wait
      - --wait-interval=30s
      - --objstore.config-file=/etc/thanos/minio-bucket.yml
      - --consistency-delay=0s
      - --http-address=0.0.0.0:19095

  thanos_query_frontend:
    container_name: query-frontend
    image: quay.io/thanos/thanos:v0.39.1
    networks:
      - grafana-network
      - querier-network
    restart: unless-stopped
    volumes:
      - ./frontend.yml:/etc/thanos/frontend.yml:ro
    command:
      - query-frontend
      - --http-address=0.0.0.0:20902
      - --query-frontend.compress-responses
      - --query-frontend.downstream-url=http://thanos_querier:29090 # querier address
      - --query-frontend.log-queries-longer-than=5s
      - --query-range.split-interval=1m
      - --query-range.response-cache-max-freshness=1m
      - --query-range.max-retries-per-request=5
      - --query-range.response-cache-config-file=/etc/thanos/frontend.yml
      - --cache-compression-type=snappy
    ports:
      - 20902:20902

  grafana:
    container_name: grafana-lab
    image: grafana/grafana-enterprise
    restart: unless-stopped
    # depends_on:
    #   - influxdb
    networks:
      - grafana-network
    # image: grafana/grafana-enterprise:12.0.1-ubuntu full ubuntu base image
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=ahmad
      - GF_SECURITY_ADMIN_PASSWORD=ahmad998
    #   - GF_PLUGINS_PREINSTALL=grafana-clock-panel, grafana-simple-json-datasource, grafana-synthetic-monitoring-app
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  minio-storage: {}
  prometheus0-eu1-storage: {}
  prometheus0-us1-storage: {}
  prometheus1-us1-storage: {}
  grafana-storage: {}

networks:
  prometheus-eu-network:
  prometheus-us0-network:
  prometheus-us1-network:
  ocs-network:
  querier-network:
  grafana-network:
